import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
    Lightbulb,
    Clock,
    TrendingUp,
    Hash,
    Sparkles,
    Calendar,
    Target,
    Zap
} from 'lucide-react';
import { recommendationsAPI } from '../services/advanced';
import toast from 'react-hot-toast';

export default function RecommendationsPage() {
    const [loading, setLoading] = useState(false);
    const [topicSuggestions, setTopicSuggestions] = useState([]);
    const [optimalTimes, setOptimalTimes] = useState([]);
    const [contentIdeas, setContentIdeas] = useState([]);

    useEffect(() => {
        fetchRecommendations();
    }, []);

    const fetchRecommendations = async () => {
        setLoading(true);
        try {
            const [topics, times, ideas] = await Promise.all([
                recommendationsAPI.getTopicSuggestions(1).catch(() => ({ data: { topics: mockTopics } })),
                recommendationsAPI.getOptimalTimes(1).catch(() => ({ data: { optimal_times: mockOptimalTimes } })),
                recommendationsAPI.getContentIdeas(1).catch(() => ({ data: { ideas: mockContentIdeas } }))
            ]);

            setTopicSuggestions(topics.data.topics || mockTopics);
            setOptimalTimes(times.data.optimal_times || mockOptimalTimes);
            setContentIdeas(ideas.data.ideas || mockContentIdeas);
        } catch (error) {
            console.error('Failed to load recommendations:', error);
            // Fallback to mock data
            setTopicSuggestions(mockTopics);
            setOptimalTimes(mockOptimalTimes);
            setContentIdeas(mockContentIdeas);
        } finally {
            setLoading(false);
        }
    };

    const mockTopics = [
        { topic: 'Web Development', score: 92, reason: 'High engagement in past posts', trending: true },
        { topic: 'AI & Machine Learning', score: 88, reason: 'Growing interest in your network', trending: true },
        { topic: 'Design Inspiration', score: 85, reason: 'Popular among followers', trending: false },
        { topic: 'Productivity Tips', score: 82, reason: 'High engagement rate', trending: false },
    ];

    const mockOptimalTimes = [
        { day: 'Monday', time: '9:00 AM', engagement: 'High', reason: 'Best for professional content' },
        { day: 'Wednesday', time: '2:00 PM', engagement: 'High', reason: 'Peak afternoon activity' },
        { day: 'Friday', time: '7:00 PM', engagement: 'Medium', reason: 'Weekend wind-down' },
        { day: 'Sunday', time: '11:00 AM', engagement: 'Medium', reason: 'Casual browsing time' },
    ];

    const mockContentIdeas = [
        {
            title: 'Behind-the-scenes: My development setup',
            category: 'Tutorial',
            platforms: ['Instagram', 'Twitter'],
            estimatedEngagement: 'High',
            tags: ['#coding', '#workspace', '#devlife']
        },
        {
            title: 'Top 5 JavaScript tips for beginners',
            category: 'Educational',
            platforms: ['Twitter', 'LinkedIn'],
            estimatedEngagement: 'Very High',
            tags: ['#javascript', '#webdev', '#programming']
        },
        {
            title: 'Weekend project showcase',
            category: 'Showcase',
            platforms: ['Instagram', 'Twitter'],
            estimatedEngagement: 'Medium',
            tags: ['#project', '#showcase', '#coding']
        }
    ];

    const getEngagementColor = (level) => {
        switch (level?.toLowerCase()) {
            case 'very high':
                return 'text-green-600 dark:text-green-400 bg-green-100 dark:bg-green-900/30';
            case 'high':
                return 'text-blue-600 dark:text-blue-400 bg-blue-100 dark:bg-blue-900/30';
            case 'medium':
                return 'text-yellow-600 dark:text-yellow-400 bg-yellow-100 dark:bg-yellow-900/30';
            default:
                return 'text-gray-600 dark:text-gray-400 bg-gray-100 dark:bg-gray-700';
        }
    };

    return (
        <div className="space-y-12 pb-12">
            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-8">
                <div>
                    <h1 className="text-4xl font-black uppercase tracking-tighter text-white">
                        Oracle Feed
                    </h1>
                    <p className="text-white/40 font-medium mt-2">
                        Reality-warping content strategies generated by the void.
                    </p>
                </div>
                <button
                    onClick={fetchRecommendations}
                    className="flex items-center gap-3 px-8 py-4 bg-white text-black rounded-2xl font-black uppercase tracking-widest hover:scale-105 active:scale-95 transition-all shadow-neon-white"
                >
                    <Sparkles className="w-5 h-5 fill-current" />
                    Recalibrate
                </button>
            </div>

            {/* Trending Topics */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="glass-card"
            >
                <div className="flex items-center gap-4 mb-10">
                    <div className="w-10 h-10 bg-vivid-purple/10 border border-vivid-purple/20 rounded-xl flex items-center justify-center">
                        <Hash className="w-5 h-5 text-vivid-purple" />
                    </div>
                    <h2 className="text-xl font-black uppercase tracking-tight text-white">
                        Vibe Resonance
                    </h2>
                </div>

                <div className="grid md:grid-cols-2 gap-6">
                    {topicSuggestions.map((topic, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: index * 0.1 }}
                            className="p-8 bg-white/5 border border-white/10 rounded-[24px] hover:border-vivid-purple/30 transition-all group"
                        >
                            <div className="flex items-start justify-between mb-4">
                                <div className="flex-1">
                                    <h3 className="text-xl font-black uppercase tracking-tight text-white flex items-center gap-3">
                                        {topic.topic}
                                        {topic.trending && (
                                            <TrendingUp className="w-4 h-4 text-vivid-purple animate-pulse" />
                                        )}
                                    </h3>
                                    <p className="text-xs font-black uppercase tracking-widest text-white/30 mt-3">
                                        {topic.reason}
                                    </p>
                                </div>
                                <div className="text-right pl-4">
                                    <p className="text-3xl font-black text-vivid-purple">
                                        {topic.score}
                                    </p>
                                    <p className="text-[10px] font-black uppercase tracking-widest text-white/20">Power</p>
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </motion.div>

            {/* Optimal Posting Times */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="glass-card"
            >
                <div className="flex items-center gap-4 mb-10">
                    <div className="w-10 h-10 bg-electric-blue/10 border border-electric-blue/20 rounded-xl flex items-center justify-center">
                        <Clock className="w-5 h-5 text-electric-blue" />
                    </div>
                    <h2 className="text-xl font-black uppercase tracking-tight text-white">
                        Temporal Sync
                    </h2>
                </div>

                <div className="grid md:grid-cols-2 gap-6">
                    {optimalTimes.map((time, index) => (
                        <div
                            key={index}
                            className="p-8 bg-white/5 border border-white/10 rounded-[24px] hover:bg-white/10 transition-all group"
                        >
                            <div className="flex items-center justify-between mb-4">
                                <div className="flex items-center gap-4">
                                    <div className="w-10 h-10 bg-white/5 rounded-xl flex items-center justify-center">
                                        <Calendar className="w-5 h-5 text-electric-blue" />
                                    </div>
                                    <div>
                                        <p className="text-lg font-black uppercase tracking-tight text-white">
                                            {time.day}
                                        </p>
                                        <p className="text-xs font-black uppercase tracking-widest text-white/30">
                                            {time.time}
                                        </p>
                                    </div>
                                </div>
                                <span className={`px-4 py-1.5 text-[10px] font-black uppercase tracking-widest rounded-full ${getEngagementColor(time.engagement).replace('bg-green-100 dark:bg-green-900/30', 'bg-neon-green/10 border border-neon-green/20').replace('bg-blue-100 dark:bg-blue-900/30', 'bg-electric-blue/10 border border-electric-blue/20').replace('bg-yellow-100 dark:bg-yellow-900/30', 'bg-cyber-yellow/10 border border-cyber-yellow/20')}`}>
                                    {time.engagement}
                                </span>
                            </div>
                            <p className="text-xs font-medium text-white/40 mt-4 italic">
                                "{time.reason}"
                            </p>
                        </div>
                    ))}
                </div>
            </motion.div>

            {/* Content Ideas */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="glass-card"
            >
                <div className="flex items-center gap-4 mb-10">
                    <div className="w-10 h-10 bg-hot-pink/10 border border-hot-pink/20 rounded-xl flex items-center justify-center">
                        <Lightbulb className="w-5 h-5 text-hot-pink" />
                    </div>
                    <h2 className="text-xl font-black uppercase tracking-tight text-white">
                        Alpha Blueprints
                    </h2>
                </div>

                <div className="space-y-6">
                    {contentIdeas.map((idea, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.4 + index * 0.1 }}
                            className="p-8 bg-white/5 border border-white/10 rounded-[32px] hover:border-hot-pink/30 transition-all group"
                        >
                            <div className="flex flex-col md:flex-row items-start justify-between gap-6 mb-6">
                                <div className="flex-1">
                                    <div className="flex items-center gap-3 mb-4">
                                        <Zap className="w-5 h-5 text-hot-pink fill-current" />
                                        <h3 className="text-2xl font-black uppercase tracking-tight text-white group-hover:text-hot-pink transition-colors">
                                            {idea.title}
                                        </h3>
                                    </div>
                                    <p className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-6">
                                        Classification: {idea.category}
                                    </p>
                                    <div className="flex flex-wrap gap-3">
                                        {idea.tags?.map((tag, tagIndex) => (
                                            <span
                                                key={tagIndex}
                                                className="px-4 py-2 bg-white/5 border border-white/10 text-white/60 text-[10px] font-black uppercase tracking-widest rounded-xl hover:text-white hover:bg-white/10 transition-all"
                                            >
                                                {tag}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                                <span className={`px-5 py-2 text-[10px] font-black uppercase tracking-widest rounded-full whitespace-nowrap ${getEngagementColor(idea.estimatedEngagement).replace('bg-green-100', 'bg-neon-green/10 border border-neon-green/20').replace('bg-blue-100', 'bg-electric-blue/10 border border-electric-blue/20')}`}>
                                    Potential: {idea.estimatedEngagement}
                                </span>
                            </div>
                            <div className="flex items-center gap-3 pt-6 border-t border-white/5">
                                <Target className="w-4 h-4 text-white/20" />
                                <p className="text-[10px] font-black uppercase tracking-[0.2em] text-white/20">
                                    Target Platforms: {idea.platforms?.join(' // ') || 'Universal'}
                                </p>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </motion.div>

            {/* Quick Tips */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
                className="relative overflow-hidden rounded-[32px] p-12 bg-white text-black"
            >
                <div className="relative z-10">
                    <h3 className="text-3xl font-black uppercase tracking-tighter mb-8 flex items-center">
                        <Sparkles className="w-8 h-8 mr-4 fill-black" />
                        Void Wisdom
                    </h3>
                    <div className="grid md:grid-cols-3 gap-8">
                        <div className="space-y-2">
                            <div className="w-8 h-1 bg-black mb-4" />
                            <p className="font-bold uppercase tracking-tight leading-tight">Sync temporal streams for maximum impact.</p>
                        </div>
                        <div className="space-y-2">
                            <div className="w-8 h-1 bg-black mb-4" />
                            <p className="font-bold uppercase tracking-tight leading-tight">Ramp engagement by riding trending waves.</p>
                        </div>
                        <div className="space-y-2">
                            <div className="w-8 h-1 bg-black mb-4" />
                            <p className="font-bold uppercase tracking-tight leading-tight">Hybridize genres to break the algorithm.</p>
                        </div>
                    </div>
                </div>
                {/* Decorative */}
                <div className="absolute top-0 right-0 w-64 h-64 bg-electric-blue/20 blur-[80px] rounded-full" />
            </motion.div>
        </div>
    );
}
